name: CI/CD

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - '.github/**'
      - 'README.md'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run tests
        shell: bash
        run: echo "run tests here"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        uses: docker/build-push-action@v4
        with:
          context: app
          push: false
          tags: ${{ github.sha }}

  semantic-release:
    name: 'Semantic Release'
    needs: [ tests, build ]
    # We run semantic-release only on merges to main branch
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # To avoid race conditions, this makes sure semantic-release is async
    concurrency: 'semantic-release'
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_git_tag: ${{ steps.semantic.outputs.new_release_git_tag }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: 'Setup Node'
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.15.0

      - name: Semantic bot token
        id: bot-token
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.SEMANTIC_APP_ID }}
          private_key: ${{ secrets.SEMANTIC_APP_PRIVATE_KEY }}

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v3.4.2
        with:
          semantic_version: 19.0.5
          extra_plugins: |
            conventional-changelog-conventionalcommits@5.0.0
        env:
          GITHUB_TOKEN: ${{ steps.bot-token.outputs.token }}

  publish:
    if: needs.semantic-release.outputs.new_release_published == 'true'
    needs: semantic-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        uses: docker/build-push-action@v4
        with:
          context: app
          push: true
          tags: ${{ needs.semantic-release.outputs.new_release_git_tag }}