name: Lint Python and Terraform

on: push

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Python Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          max-line-length: "120"
  terraform-format:
    runs-on: ubuntu-latest
    name: Check terraform files for correct formatting.
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
        with:
          path: .
      - name: terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: .
